---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
devtools::load_all()
library(remi)
```

Reading in dataset: 
To-Do: get rid of cell markers! 
- create tutorial for Seurat object integration
```{r}
adeno.data <- read.csv("~/Projects/rotation_remi/data/test/bulk_flowsort/U01Adeno_logged.csv",
                       row.names=1)
colnames(adeno.data) <- gsub("_CD45", "_I", colnames(adeno.data))
colnames(adeno.data) <- gsub("_CD31", "_E", colnames(adeno.data))
colnames(adeno.data) <- gsub("_CD10", "_F", colnames(adeno.data))
colnames(adeno.data) <- gsub("_Ep", "_M", colnames(adeno.data))
```

Set up data for remi
```{r}
celltypes <- c("I", "E", "F", "M")
cellexp.list <- setupData(adeno.data, celltypes, 5, filter=T)
remi.interactome <- remi(celltypes, cellexp.list, seed=25)
```

Visualize interactome players 
```{r}
grid.col <- c("F"='#BB6A23', 
              I="#195188", 
              M="#00503C", 
              E="#AC371F")
ChordPlot(remi.interactome, grid.col=grid.col)
```

Re-running REMI with Lung TMI genes
```{r}

```

Write to Cytoscape
```{r}
# Edgelist file
write.csv(unique(sig.maxedges[,c("node1", "node2", "weight")]),
          file="caberNETedges_0.csv", quote=F, row.names=F)

# Nodes file
sig.nodes <- unique(c(paste0(sig.maxedges$node1), paste0(sig.maxedges$node2)))
net.celltypes <- unlist(lapply(sig.nodes, function(x) {strsplit(x, "_")[[1]][1]}))
nodetype <- rep("L", length(sig.nodes))
nodetype[which(sig.nodes %in% cab.results$lrnet$mat$R)] <- "R"
lungtmi.nodes <- cbind(sig.nodes, net.celltypes, nodetype)
colnames(lungtmi.nodes) <- c("name", "CellType", "NodeType")
write.csv(lungtmi.nodes, file="caberNET_nodes_062020.csv", row.names=F, quote=F)
```

```{r}
GetDSNeighbors <- function(obj, R) {
  receive.cell <- strsplit(R, "_")[[1]][1]
  downstream.edges <- attr(E(remi.interactome$ir$net[[receive.cell]])[from(R)], "vnames")
  neighbor.nodes <- unique(unlist(lapply(downstream.edges, function(x) {strsplit(x, "\\|")})))
  neighbor.ec <- remi.interactome$ir$allec[setdiff(neighbor.nodes, R)]
  return(sort(neighbor.ec, decreasing=T))
}
```

Downstream neighbors of receptor of interest
```{r}
test <- GetDSNeighbors(remi.interactome, "F_TNFRSF1A")
```











